language: php
sudo: required

env:
  global:
  - REPO=orangehrm/orangehrm-rabbitmq
  - TAG=3.8.4-management

matrix:
    include:
        - os: linux
          dist: trusty       

services:
  - docker

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
  - uname -a
  - php --version
  - docker version
  - composer self-update
  - docker build -t $REPO:$TAG docker-image

install:
  - docker-compose up -d
  - docker ps

script:
  - docker ps

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $REPO:$TAG

